export const ActionsTypes={
    DELETE_POSTE:'DELETE_POSTE',
    GET_POSTES_SUCCESS:'GET_POSTES_REQUEST',
    GET_POSTES_FAILED:'GET_POSTES_REQUEST',
    ADD_POSTES:'ADD_POSTES',
    UPDATE_POSTE:'UPDATE_POSTE',
    GET_SINGLE_POSTE:'GET_SINGLE_POSTE',
} ;